# Generated by Django 3.0.3 on 2020-08-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('surname', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=264, unique=True)),
                ('password', models.CharField(max_length=264)),
            ],
        ),
    ]
