# Generated by Django 3.0.3 on 2020-08-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exe01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
