# Generated by Django 3.0.3 on 2020-08-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exe01', '0002_remove_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='pippo@pippo.it', max_length=254),
            preserve_default=False,
        ),
    ]
